project:
  type: website
  output-dir: docs
website:
  title: "Crayfisher"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Our Philosophy
      # - icon: github
      #   href: https://github.com
      # - icon: linkedin
      #   href: https://linkedin.com

format:
  html:
    theme: vapor
    toc: true
    css: styles.css